#!/bin/bash
# OpenAI API Key Setup Guide

echo "========================================="
echo "OpenAI API Key Setup for AccessGate AI"
echo "========================================="
echo ""
echo "📋 Step 1: Get your OpenAI API Key"
echo "   1. Go to: https://platform.openai.com/api-keys"
echo "   2. Sign in (or create an account)"
echo "   3. Click 'Create new secret key'"
echo "   4. Copy the key (starts with 'sk-')"
echo ""
echo "📝 Step 2: Add the key to your .env file"
echo "   Run this command (replace YOUR_KEY with your actual key):"
echo ""
echo "   cd apps/api"
echo "   echo 'OPENAI_API_KEY=sk-YOUR_ACTUAL_KEY_HERE' >> .env"
echo ""
echo "   Or manually edit apps/api/.env and replace:"
echo "   OPENAI_API_KEY=sk-your-key-here"
echo "   with your actual key"
echo ""
echo "🔄 Step 3: Restart the backend server"
echo "   The uvicorn server should auto-reload, but if not:"
echo "   - Press Ctrl+C in the terminal running the backend"
echo "   - Run: uvicorn main:app --reload --port 8000"
echo ""
echo "✅ Step 4: Verify it's working"
echo "   You should see this message disappear from the logs:"
echo "   'WARNING: OpenAI API Key not found or package missing. Using Mock LLM.'"
echo ""
echo "💰 Cost Information:"
echo "   - GPT-3.5-turbo: ~$0.002 per request"
echo "   - For demo/portfolio: $5-20/month typical usage"
echo "   - You can set usage limits in OpenAI dashboard"
echo ""
echo "🔒 Security Reminder:"
echo "   - Never commit .env to git (already in .gitignore)"
echo "   - Don't share your API key publicly"
echo "   - Rotate keys regularly"
echo ""
echo "========================================="
